name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Azure Functions
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          azure-cli-version: 2.30.0
          azure-functions-version: 3.0.300
      - name: Deploy
        run: az functionapp deployment source config --name SecondFunctionApp02 --resource-group 481-69733883-build-and-distribute-an-app-in-app-ce --repo-url https://github.com/disys-indhu/FunctionApp3_Deploy.git
      
