name: Deploy Function App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group 481-3719fecc-build-and-distribute-an-app-in-app-ce \
            --name SecondFunctionApp02 \
            --src /FunctionApp3/FunctionApp3.zip
